baskel:
    resource: "@BaskelBundle/Resources/config/routing.yml"
    prefix:   /

club_club:
    resource: "@ClubBundle/Controller/ClubController.php"
    type:     annotation

club:
    resource: "@ClubBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

event_categorie:
    resource: "@EventBundle/Controller/CategorieController.php"
    type:     annotation

event_event:
    resource: "@EventBundle/Controller/EventController.php"
    type:     annotation

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
