meeting_calendrier:
    path:     /calendrier
    defaults: { _controller: "BaskelBundle:Meeting:calendar" }
    methods:  GET

meeting_index:
    path:     /
    defaults: { _controller: "BaskelBundle:Meeting:index" }
    methods:  GET

meeting_show:
    path:     /{id}/show
    defaults: { _controller: "BaskelBundle:Meeting:show" }
    methods:  GET

meeting_new:
    path:     /new
    defaults: { _controller: "BaskelBundle:Meeting:new" }
    methods:  [GET, POST]

meeting_edit:
    path:     /{id}/edit
    defaults: { _controller: "BaskelBundle:Meeting:edit" }
    methods:  [GET, POST]

meeting_delete:
    path:     /{id}/delete
    defaults: { _controller: "BaskelBundle:Meeting:delete" }
    methods:  DELETE
